name = "KohnShamResolution"
uuid = "2d6a71d3-f4fe-4c59-9782-ebc44d5ef3e9"
authors = ["Th√©o Duez <42682941+Theozeud@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LambertW = "984bce1d-4616-540c-a9ee-88d1112d94c9"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Arpack = "0.5.4"
BandedMatrices = "1.9.2"
BlockDiagonals = "0.1.42"
FillArrays = "1.13.0"
IncompleteLU = "0.2.1"
IterativeSolvers = "0.9.4"
Krylov = "0.9.10"
KrylovKit = "0.9.5"
LinearOperators = "2.9.0"
LoopVectorization = "0.12.171"
Optim = "1.11.0"
SparseArrayKit = "0.2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
